### ISSUE TITLE
How to use the *.exe on Ubuntu

### ISSUE THREAD

**Issue by billjwilliamson** [r-barnes/ArcRasterRescue#11]
Apologies for what might be a Ubuntu noob question, but how to use the arc_raster_rescue.exe on Ubuntu? Or does it run on some other system?

**Comment by r-barnes** [comment]
@billjwilliamson : ArcRasterRescue will work on Ubuntu (I know because this is the system I use). Usage is explained in the `README.md` file. Which part of that explanation can I clarify for you?

**Comment by billjwilliamson** [comment]
On Ubuntu, I got a successful build
```
[ 75%] Building CXX object CMakeFiles/arc_raster_rescue.exe.dir/evaluation/main.cpp.o
[100%] Linking CXX executable arc_raster_rescue.exe
[100%] Built target arc_raster_rescue.exe
```
So I tried 
`arc_raster_rescue.exe MyDEM_1SEC.gdb`
but I get
`arc_raster_rescue.exe: command not found`

**Comment by r-barnes** [comment]
As stated in the README, you should use:
```
./arc_raster_rescue.exe <path/to/geodatabase.gdb/>
```
The `./` at the beginning is important: https://unix.stackexchange.com/q/4430/9904

**Comment by billjwilliamson** [comment]
A ha, my apologies. 

Works now! Champion effort!

**Comment by r-barnes** [comment]
Yay!
