### ISSUE TITLE
DOI not working

### ISSUE THREAD

**Issue by Joeperdefloep** [r-barnes/ArcRasterRescue#15]
Thanks so much for this great tool! It really saved my day today.

I am currently writing an essay, and wanted to insert a reference. However the DOI provided ( doi: 10.5281/zenodo.4128479.) does not return anything when entered in my search bar (firefox).

Kind regards,
Joep

**Comment by r-barnes** [comment]
Joep,
Have you tried https://doi.org/10.5281/zenodo.4128479?

**Comment by Joeperdefloep** [comment]
Aah, yes that works!
Thanks!
I also had some weird outputs with some maps, so in the end I had to "rescue" them using ArcGIS.
