### ISSUE TITLE
Any movement

### ISSUE THREAD

**Issue by JimShady** [r-barnes/ArcRasterRescue#7]
Hi @r-barnes . Wondering if this went anywhere? I'm struggling with a very similar issue:

https://twitter.com/TheRealJimShady/status/1194621993464860677

**Comment by r-barnes** [comment]
@JimShady : I'm sorry, I'm strapped for time at the moment and haven't had an opportunity to work on this :-(

**Comment by JimShady** [comment]
No worries @r-barnes . Thanks for all you've done so far.
